### ISSUE TITLE
Error parsing resource: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by phumpal** [sensu-plugins/sensu-plugins-http#181]
Perhaps a sensu-go bug but passing a Host header in [v5.19.1](https://github.com/sensu/sensu-go/releases/tag/v5.19.1)

```
type: CheckConfig
api_version: core/v2
metadata:
  name: check_http_unicorn
  namespace: default
spec:
  command: check-http.rb --hostname 10.2.12.116 --port 8080 --header 'Host: mydomain.dev' --request-uri / -r true
```

results in

> Error: in /etc/sensu/conf.d/checks: error parsing resources: yaml: line 7: mapping values are not allowed in this context

Removing `--header 'Host: mydomain.dev` allows the check config to upload but without the header the check will fail.

Removing the assignment `:` prevents key value mapping of custom headers.

> CheckHttp CRITICAL: Request error: undefined method `strip' for nil:NilClass

**Comment by phumpal** [comment]
@majormoses should I move this to sensu-go or am I missing something obvious?

**Comment by phumpal** [comment]
I solve this by "fixing" my yaml

```
type: CheckConfig
api_version: core/v2
metadata:
  name: check_http_unicorn
  namespace: default
spec:
  command: |
    check-http.rb --hostname 10.2.12.116 --port 8080 --header 'Host: mydomain.dev' --request-uri / -r true
```
